project_name: func

before:
  hooks:
    - go mod tidy
    - make init-releaser

builds:
  - env:
      - CGO_ENABLED=0
      - GO111MODULE=on
      - GOPROXY=https://gocenter.io
    goos:
      - linux
      - darwin
    goarch:
      - amd64
    ldflags:
      - -s -w -X github.com/moritzzimmer/func/cmd.version={{.Version}} -X github.com/moritzzimmer/func/cmd.commit={{.ShortCommit}} -X github.com/moritzzimmer/func/cmd.date={{.Date}}

archives:
  - files:
      - none*

release:
  prerelease: true

brews:
  - name: func
    tap:
      owner: moritzzimmer
      name: homebrew-tap
    description: "Func is a CLI app to simplify development and deployment of AWS Lambda functions using Go and Terraform."
    homepage: "https://github.com/moritzzimmer/func"
    license: "MIT"
    install: |
      bin.install "func"
    test: |
      system "#{bin}/func", "version"
