project_name: func
before:
  hooks:
    - go mod download
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
      - GO111MODULE=on
      - GOPROXY=https://gocenter.io
    hooks:
      pre: packr2
      post: packr2 clean
    goos:
      - linux
      - darwin
    goarch:
      - amd64
    ldflags:
      - -s -w -X github.com/spring-media/func/cmd.version={{.Version}} -X github.com/spring-media/func/cmd.commit={{.ShortCommit}} -X github.com/spring-media/func/cmd.date={{.Date}}
archives:
  - files:
      - none*
release:
  prerelease: true
