project_name: func

before:
  hooks:
    - go mod download
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
      - GO111MODULE=on
      - GOPROXY=https://gocenter.io
    hooks:
      pre: packr2
      post: packr2 clean
    goos:
      - linux
      - darwin
    goarch:
      - amd64
    ldflags:
      - -s -w -X github.com/moritzzimmer/func/cmd.version={{.Version}} -X github.com/moritzzimmer/func/cmd.commit={{.ShortCommit}} -X github.com/moritzzimmer/func/cmd.date={{.Date}}

archives:
  - files:
      - none*

release:
  prerelease: true

brews:
  - name: func
    github:
      owner: moritzzimmer
      name: homebrew-tap
    install: |
      bin.install "func"
    test: |
      system "#{bin}/func", "version"
