name: release

on:
    push:
        branches-ignore:
        - '**'
        tags:
        - 'v*.*.*'

jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            -
                name: Checkout
                uses: actions/checkout@v2
            -
                name: Set up Go
                uses: actions/setup-go@v2
                with:
                  go-version: 1.15.x
            -
                name: Unshallow
                run: git fetch --prune --unshallow
            -
                name: Run GoReleaser
                uses: goreleaser/goreleaser-action@v2
                with:
                  version: latest
                  args: release --rm-dist
                env:
                  GITHUB_TOKEN: ${{ secrets.CUSTOM_GITHUB_TOKEN }}